### PR TITLE
File sharing feature

### PR DESCRIPTION
**Pull request by joseavilasg09**
Hi there again. In this pull request, I've implemented the file sharing feature. I've made a lot of changes, so I will not explain everything. Just the important ones.

**Changes:**
- Added a new column to files table, called `visibility`, which supports only three values: `public`, `private` or `limited`. When set to "public", everyone can access the file. When it is set to "private", no one can do it. When set to "limited", only allowed users can do this.
- Added a new table called `shared_files`, which stores `file_id` and the `shared_with_username` columns.
- Added a new route called `/checkFileVisibility/:fileID`, which will be used in the UI to retrieve whether to allow or deny public access.
- Added a new route called `/sharefile/:fileID`, which will change the `visibility` column of `files` table, and add `shared_with_username` to `shared_files` if neccesary.
- Created helper functions in the db: `add_shared_users` and `remove_shared_users`, to handle adding and removing users.
- Updated the auth middleware to allow or deny public access.
- Now, when listing files, additionally returns an array of shared usernames and an array of path and id of that path. This will be used in the UI to create the folder chain for the shared view. I'll explain them in the other pull request.
- Other changes in the models and schemes to support the new features.

I'm aware it's quite a bit of changes, but please take a look and let me know if any additional adjustments are necessary. Thank you.

### CODE REVIEW

**Comment by divyam234** [comment]
@joseavilasg09  I have some better schmea design in Mind
```sql
CREATE TABLE shared_files (
    id SERIAL PRIMARY KEY,
    file_id INT NOT NULL,
    shared_with INT NOT NULL,
    shared_by INT NOT NULL,
    parent_file_id INT NULL, -- Reference to the parent folder
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (file_id) REFERENCES files(id),
    FOREIGN KEY (shared_with) REFERENCES users(id),
    FOREIGN KEY (shared_by) REFERENCES users(id),
   FOREIGN KEY (parent_folder_id) REFERENCES folders(id)
);

CREATE TABLE permissions (
    id SERIAL PRIMARY KEY,
    shared_file_id INT NOT NULL,
    permission_level VARCHAR(255) NOT NULL,
    FOREIGN KEY (shared_file_id) REFERENCES shared_files(id)
);
```sql

**Comment by divyam234** [comment]
Also sharing feature is bit complex  to implement as you think there are diff ways .

1. Requesting shared will use sharee auth so shared user would not be able to make use of  bots as  they dont't  have access to sharee channel . To mitigate this shared user can use auth session of sharee  (currently which teledrive follows) , but its not a good approch as shared used can post risk of soft bans on sharee account by rigrously downloading shared files  on one client and what if user logout and deletes his telegram session accidently  then also it will not work.

2. To mitigate all problems above best way is to use forwarded messages to forward all  file parts  from sharee to shared user channel  first this will fix ban problem  and also if files are deleted from sharee  channel forwarded messages are deleted automatically and shared user can use their bots for downloading files.

**Comment by joseavilasg09** [comment]
Perhaps I made a mistake by not opening an issue first to share my ideas, right? As you say, it's complex and I hadn't fully considered the potential challenges with Telegram. However, it'd be really interesting to work in it. Are you planning to implement it yourself? While I may not have extensive experience with Go or Telegram, if you're short on time I'd be more than willing to lend a hand if you point me in the right direction. I don't have enough time either sometimes, but I can do my best.

**Comment by divyam234** [comment]
@joseavilasg09  I will require lot of changes also not many people will use shared instances so sharing feature is useless on  a single instance ,for simple storage options its easy to implement but for telegram  its quite challenging .It can be added in future  once enough users are using teldrive ui for now  its not  needed .

**Comment by joseavilasg09** [comment]
@divyam234 Yeah, I'm still working on learning how to write optimized code, so I understand the complexity. I'll definitely check the branch out. Thank you.

**Pull request closed without merging**
