### PR TITLE
Show folder size

### PR DESCRIPTION
**Pull request by joseavilasg09**
Hi there again. In this pull request, I've introduced an automatic folder size update for file insertions, updates, and deletions. I did it implementing triggers and functions.

**Changes:**
- Created the "update_size_function" function.
- Created the "update_folder_size_after_insert_update_delete" trigger.
- Correctly managed the migrations.

Please review and let me know if any further changes or adjustments are needed. Thank you.

### CODE REVIEW

**Comment by divyam234** [comment]
@joseavilasg09  Update trigger should only trigger on size field .
```sql
UPDATE OF size 
```

**Comment by joseavilasg09** [comment]
@divyam234 In this case, it should trigger on status too. Since it changes when a file is "deleted" to pending_deletion.

**Comment by divyam234** [comment]
> @divyam234 In this case, it should trigger on status too. Since it changes when a file is "deleted" to pending_deletion.

Yeah these two fields although size will not be updated directly through ui nut  it will be needed in rclone when is directly updated from mounted drive.

**Comment by joseavilasg09** [comment]
Alright. Changes were made.

**Pull request merged**
