### PR TITLE
Audio playback support

### PR DESCRIPTION
**Pull request by joseavilasg09**
Hello. In this PR, I've just added support for playing audio files. I was looking for an interesting npm package to handle audio playback, but could'n find it. I just used a hook for functionality and built the UI with MUI. This is how it looks:

image
Hope that's ok. If no, I'm open to suggestions if you have any.

**Changes:**

**1. Backend:**
  - Added new routes:
      - `files/audioMetadata/:fileID` for fetching audio metadata, including details like artist, title, and available cover art types (e.g., front cover, back cover) and the image extension.
      - `files/audioCoverArt/:fileID/:coverName` for fetching specific cover art.
  - Introduced the `getAudioFullMetadata` function to retrieve audio metadata using [this package](https://github.com/dhowden/tag).
  - In this function, I retrieve file parts in range intervals of 1MB. This allows us to fetch only the necessary data for metadata, rather than the entire file.
  - I also duplicated the `streamFilePart` function and renamed it like `getFilePart`, which returns a `byte` array instead of writing to a pipe. I wasn't sure of using pipes or goroutines in a loop. Also, couldn't make it work, so.

**2. Frontend:**
- Implemented a new hook `useGetAudioMetadata`, to fetch audio metadata.
- Created the `AudioPreview` component and added music playback functionality using [this package](https://www.npmjs.com/package/react-use-audio-player).
- Designed the player's UI using MUI.

Please review these changes, and let me know if any further adjustments are needed. Your feedback is greatly appreciated.

PS: Do I need to create a PR in the UI repo? I'm quite new to working with git submodules.

### CODE REVIEW

**Comment by 2640yang** [comment]
Is video playback possible?

**Comment by 2640123** [comment]
Is video playback possible?

**Comment by joseavilasg09** [comment]
@2640123, video playback is working. There are some issues with specific video types, but overall, it's working.

**Comment by divyam234** [comment]
closing this one use new one for further changes if needed in preview

**Pull request closed without merging**
